apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowebapi
spec:
  selector:
    matchLabels:
      app: gowebapi
  replicas: 2
  template:
    metadata:
      labels:
        app: gowebapi
    spec:
      containers:
      - name: gowebapi
        image: localhost:8085/gowebapi
        ports:
        - containerPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: gowebapi
spec:
  type: NodePort
  selector:
    app: gowebapi
  ports:
      - port: 8181
        targetPort: 8181
        nodePort: 31313